const router = require("express").Router();
const ctrl = require("../controllers/authController");
const { authenticate } = require("../middleware/auth");
router.post("/register", ctrl.register);
router.post("/login", ctrl.login);
router.get("/me", authenticate, ctrl.me);
router.post("/change-password", authenticate, ctrl.changePassword);
router.post("/admin/reset-password", authenticate, ctrl.adminResetPassword);
router.post("/admin/set-password", authenticate, ctrl.adminSetPassword);
router.post("/admin/create-staff", authenticate, ctrl.adminCreateStaff);
module.exports = router;
