const router = require("express").Router();
const ctrl = require("../controllers/notificationController");
const { authenticate, authorize } = require("../middleware/auth");
router.use(authenticate);
router.get("/unread-count", ctrl.getUnreadCount);
router.get("/activity", ctrl.getActivity);
router.get("/", ctrl.getForUser);
router.put("/read-all", ctrl.markAllRead);
router.put("/:id/read", ctrl.markRead);
router.delete("/:id", ctrl.remove);
router.post("/", authorize("Admin", "Dean", "ViceDean", "ExamsOfficer", "Accountant", "Registrar"), ctrl.create);
router.post("/broadcast", authorize("Admin", "Dean", "ViceDean", "ExamsOfficer", "Accountant", "Registrar"), ctrl.broadcast);
module.exports = router;
