const router = require("express").Router();
const ctrl = require("../controllers/supervisorController");
const { authenticate } = require("../middleware/auth");
router.use(authenticate);
router.get("/", ctrl.getAll);
router.get("/assignments", ctrl.getAllAssignments);
router.get("/:id", ctrl.getById);
router.get("/:id/students", ctrl.getAssignedStudents);
router.post("/:id/assign", ctrl.assignStudent);
router.delete("/assignments/:assignmentId", ctrl.unassignStudent);
module.exports = router;
