const router = require("express").Router();
const ctrl = require("../controllers/thesisController");
const { authenticate, authorize } = require("../middleware/auth");
const upload = require("../middleware/upload");
router.use(authenticate);
router.get("/my-submissions", ctrl.getMySubmissions);
router.get("/student/:studentId", ctrl.getByStudent);
router.get("/pending", authorize("Supervisor", "Admin", "Dean", "ViceDean", "Registrar", "AdminAssistant"), ctrl.getPending);
router.post("/upload", (req, res, next) => { req.uploadSubDir = "thesis"; next(); }, upload.single("file"), ctrl.upload);
router.put("/:id/review", authorize("Supervisor"), ctrl.review);
router.post("/:id/remarks", authorize("Supervisor", "Admin", "Student"), ctrl.addRemark);
router.get("/:id/remarks", authorize("Supervisor", "Admin", "Student"), ctrl.getRemarks);
module.exports = router;
